import 'package:sdui_engine/src/ir/model/layout_protocol.dart';

import 'widget_schema.dart';

/// The engine's built-in template language, declared compile-side.
///
/// This is the single source of truth for every identifier the built-in
/// language accepts — widget schemas, command types, motion names, and
/// expression function names — with **no Flutter or runtime dependency**, so
/// a build-time or server-side compiler validates templates against exactly
/// the language a device will interpret.
///
/// The runtime keeps its own registrations (widget specs carry rendering,
/// drivers carry behavior); `builtin_language_parity_test.dart` asserts the
/// two sides never drift: every runtime registration must match its entry
/// here, and vice versa. Add a widget/command/motion/function by declaring
/// it here first, then implementing it runtime-side.
abstract final class BuiltinLanguage {
  /// Widget type -> structural schema (kind, layout protocols).
  static const Map<String, WidgetSchema> widgets = {
  'absorb_pointer': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'align': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'anchor': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'anchor_scope': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'app_bar': WidgetSchema(kind: WidgetKind.slot, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'aspect_ratio': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'auto_scroll': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'backdrop_filter': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'badge': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'baseline': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'center': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'chart': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'checkbox': WidgetSchema(kind: WidgetKind.bound, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'circular_progress_indicator': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'clip_oval': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'clip_rect': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'clip_rrect': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'collapsing_header': WidgetSchema(kind: WidgetKind.builder, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.box),
  'color_filtered': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'column': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'constrained_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'container': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'cupertino_switch': WidgetSchema(kind: WidgetKind.bound, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'custom_scroll_view': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.sliver),
  'decorated_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'default_tab_controller': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'dismissible': WidgetSchema(kind: WidgetKind.action, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'divider': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'dropdown': WidgetSchema(kind: WidgetKind.bound, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'expanded': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'fitted_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'flex': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'flexible': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'fractionally_sized_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'grid_view': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'icon': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'ignore_pointer': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'image': WidgetSchema(kind: WidgetKind.slot, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'image_filtered': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'indexed_stack': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'interactive_viewer': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'intrinsic_height': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'intrinsic_width': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'limited_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'linear_progress_indicator': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'list_body': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'list_tile': WidgetSchema(kind: WidgetKind.slot, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'list_view': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'loading_indicator': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'nested_scroll_view': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: null),
  'offstage': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'opacity': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'overflow_bar': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'overflow_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'padding': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'page_view': WidgetSchema(kind: WidgetKind.action, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'physical_model': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'positioned': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'positioned_fill': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'radio': WidgetSchema(kind: WidgetKind.bound, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'refresh_indicator': WidgetSchema(kind: WidgetKind.action, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'rich_text': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'rotated_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'row': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'safe_area': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'scaffold': WidgetSchema(kind: WidgetKind.slot, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'scratch_card': WidgetSchema(kind: WidgetKind.action, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'scrollbar': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'serpentine': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'serpentine_row': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'shader_mask': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'single_child_scroll_view': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'sized_overflow_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'sizedbox': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'skeleton': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'slider': WidgetSchema(kind: WidgetKind.bound, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'sliver_app_bar': WidgetSchema(kind: WidgetKind.slot, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.box),
  'sliver_fill_remaining': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.box),
  'sliver_grid': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.box),
  'sliver_list': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.box),
  'sliver_padding': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.sliver),
  'sliver_persistent_header': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.box),
  'sliver_to_box_adapter': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.sliver, childProtocol: LayoutProtocol.box),
  'spacer': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'speech_balloon': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'spin_grid': WidgetSchema(kind: WidgetKind.action, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'stack': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'swipe_indicator': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'swipe_layout': WidgetSchema(kind: WidgetKind.action, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'swipe_pane': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'tab': WidgetSchema(kind: WidgetKind.slot, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'tab_bar': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'tab_bar_view': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'text': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'text_field': WidgetSchema(kind: WidgetKind.bound, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'toggle': WidgetSchema(kind: WidgetKind.bound, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'tooltip': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'transform': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'unconstrained_box': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'vertical_divider': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'video': WidgetSchema(kind: WidgetKind.action, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'visibility': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  'wrap': WidgetSchema(kind: WidgetKind.eager, produces: LayoutProtocol.box, childProtocol: LayoutProtocol.box),
  };

  /// Engine-owned command types (drivers are sealed — see Engine.initialize).
  static const Set<String> commands = {
  'anchoring',
  'app_storage',
  'modal',
  'navigate',
  'net',
  'scroll',
  'secure_storage',
  'set',
  'sys_haptic',
  'toast',
  };

  /// Motion atoms and composite preset names accepted by `_motion`.
  static const Set<String> motions = {
  'blink',
  'blur',
  'blur_in',
  'bounce',
  'color_in',
  'drop',
  'fade',
  'fade_in',
  'fade_scale',
  'fade_slide_down',
  'fade_slide_left',
  'fade_slide_right',
  'fade_slide_up',
  'flip_fade_in',
  'flip_in',
  'float',
  'move',
  'pop_in',
  'pulse',
  'raise',
  'reveal',
  'reveal_down',
  'reveal_left',
  'reveal_right',
  'reveal_up',
  'rotate',
  'rotate_in',
  'saturate',
  'scale',
  'shake',
  'shimmer',
  'slide_down',
  'slide_left',
  'slide_right',
  'slide_up',
  'spin',
  'swing',
  'tada',
  'tint',
  'wobble',
  'zoom_in',
  };

  /// Registered expression function names accepted in `${...}` calls.
  static const Set<String> functions = {
  'abs',
  'bool',
  'capitalize',
  'ceil',
  'clamp',
  'comma',
  'concat',
  'contains',
  'currency',
  'default',
  'ends_with',
  'first',
  'floor',
  'format',
  'get',
  'has',
  'int',
  'join',
  'keys',
  'last',
  'len',
  'lerp',
  'lower',
  'max',
  'merge',
  'min',
  'mix',
  'num',
  'pad_end',
  'pad_start',
  'percent',
  'range',
  'repeat',
  'replace',
  'reversed',
  'round',
  'set_path',
  'sorted',
  'split',
  'starts_with',
  'str',
  'substring',
  'sum',
  'trim',
  'type',
  'update_at',
  'upper',
  'values',
  };
}
